### PR TITLE
add js test library

### PR DESCRIPTION
**Pull request by haruair**
I added testing libraries for the time being. May we need to integrate the script with Appveyor. Please review the changes. @justinyoo @bestalign

### CODE REVIEW

**Comment by justinyoo** [comment]
@haruair Question: Do those test JS libraries get published when we deploy this app onto production?

**Comment by haruair** [comment]
@justinyoo Yes, it looks dirty. The repository hold all dependencies from Bower, even I added the libraries as `devDependencies` in `bower.json`.

@bestalign Any ideas?

**Comment by justinyoo** [comment]
@bestalign So, as long as the test JS libraries are in the devDependencies section, it should be OK for deployment, right?

@haruair Is this PR just to include test JS libraries?

**Comment by haruair** [comment]
@justinyoo Yes. `chai`, `mocha`, `mocha-jquery`, and `bower.json` only.

**Comment by justinyoo** [comment]
Cool.

**Comment by bestalign** [comment]
@justinyoo Isn't wwwroot folder only used for deployment? I believe all library files are NOT NECESSARY because they are automatically downloaded when users build the project.

**Comment by justinyoo** [comment]
@bestalign The `wwwroot` directory is only used for deployment and contains static files like .html, .css, .json, .js and so forth. What's your concern?

**Pull request merged**
